apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-ro
  namespace: apache-ns
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.56
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: apache
