apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-ro
  namespace: apache-ns
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.56
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: apache
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: apache-ro
  namespace: apache-ns
spec:
  selector:
    matchLabels:
      app: apache
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-ro
    scaleDown: onsuccess
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}